const char HTML_HOME[] =
"<!DOCTYPE html><html><head><meta charset='UTF-8'><title>Estação</title>"
"<style>body{font-family:sans-serif;text-align:center;background:#eef;margin:0;padding:10px}"
"h2{margin-top:0}.graf{margin:10px auto;width:90%;max-width:360px;height:100px;border:1px solid #ccc}"
"canvas{width:100%%;height:100%}.txt{margin:4px;font-weight:bold;font-size:15px}</style>"
"<script>"
"let dados={temp:[],hum:[],pres:[]};const LIM=50;"
"function add(val,arr){arr.push(val);if(arr.length>LIM)arr.shift();}"
"function desenhar(id,data,color){let c=document.getElementById(id),ctx=c.getContext('2d');"
"ctx.clearRect(0,0,c.width,c.height);ctx.beginPath();ctx.strokeStyle=color;"
"let h=c.height,w=c.width,max=Math.max(...data),min=Math.min(...data);"
"for(let i=0;i<data.length;i++){let x=i*(w/LIM),y=h-(data[i]-min)/(max-min+0.1)*h;ctx.lineTo(x,y);}ctx.stroke();}"
"function att(){fetch('/estado').then(r=>r.json()).then(d=>{"
"add(d.temp,dados.temp);add(d.hum,dados.hum);add(d.pres,dados.pres);"
"document.getElementById('t').innerText=d.temp.toFixed(1)+' °C (min: '+d.tmin+' / max: '+d.tmax+')';"
"document.getElementById('h').innerText=d.hum.toFixed(1)+' % (min: '+d.hmin+' / max: '+d.hmax+')';"
"document.getElementById('p').innerText=d.pres.toFixed(1)+' kPa (min: '+d.pmin+' / max: '+d.pmax+')';"
"document.getElementById('alt').innerText=d.alt.toFixed(1)+' m';"
"desenhar('gtemp',dados.temp,'red');"
"desenhar('ghum',dados.hum,'blue');"
"desenhar('gpres',dados.pres,'green');});}"
"setInterval(att,1000);window.onload=att;"
"</script></head><body>"
"<h2>Estação Meteorológica</h2>"
"<div class='txt' id='t'>--</div><canvas id='gtemp' class='graf' width='360' height='100'></canvas>"
"<div class='txt' id='h'>--</div><canvas id='ghum' class='graf' width='360' height='100'></canvas>"
"<div class='txt' id='p'>--</div><canvas id='gpres' class='graf' width='360' height='100'></canvas>"
"<div class='txt'>Altitude estimada: <span id='alt'>--</span></div>"
"<br><button onclick=\"location.href='/config'\">Ir para Configuração</button>"
"</body></html>";

const char HTML_CONFIG[] =
"<!DOCTYPE html><html><head><meta charset='UTF-8'><title>Configurar Limites</title>"
"<style>body{font-family:sans-serif;text-align:center;background:#f4f4f4;margin:0;padding:10px}"
"input{width:60px;padding:4px;margin:4px}label{display:block;margin-top:10px}"
".botao{padding:8px 16px;margin-top:15px;border-radius:6px;background:#ccc;border:none;cursor:pointer}</style>"
"<script>function enviar(){let qs='';['temp','hum','pres'].forEach(p=>{['min','max','ofs'].forEach(s=>{"
"let v=document.getElementById(p+s).value;if(v)qs+=p+s+'='+v+'&'})});fetch('/config?'+qs.slice(0,-1))}</script>"
"</head><body><h2>Configurar Limites e Offsets</h2>"
"<form onsubmit='enviar();return false;'>"
"<label>Temperatura: Min <input id='tempmin' type='number'> Max <input id='tempmax' type='number'> Offset <input id='tempofs' type='number'></label>"
"<label>Umidade: Min <input id='hummin' type='number'> Max <input id='hummax' type='number'> Offset <input id='humofs' type='number'></label>"
"<label>Pressão: Min <input id='presmin' type='number'> Max <input id='presmax' type='number'> Offset <input id='presofs' type='number'></label>"
"<button class='botao' type='submit'>Salvar</button></form>"
"<button class='botao' onclick=\"location.href='/'\">Voltar</button></body></html>";